/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube018: THREE.Mesh
    Cube018_1: THREE.Mesh
    Desk_low: THREE.Mesh
    feet_low: THREE.Mesh
  }
  materials: {
    main_body: THREE.MeshStandardMaterial
    small_screen: THREE.MeshStandardMaterial
  }
}

export const StandingDesk = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/standing_desk.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="upper_frame_low" userData={{ name: 'upper_frame_low' }}>
          <mesh
            name="Cube018"
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={materials.main_body}
          />
          <mesh
            name="Cube018_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials.small_screen}
          />
        </group>
        <mesh
          name="Desk_low"
          castShadow
          receiveShadow
          geometry={nodes.Desk_low.geometry}
          material={materials.main_body}
          userData={{ name: 'Desk_low' }}
        />
        <mesh
          name="feet_low"
          castShadow
          receiveShadow
          geometry={nodes.feet_low.geometry}
          material={materials.main_body}
          userData={{ name: 'feet_low' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/standing_desk.glb')
